### ISSUE TITLE
Interface

### ISSUE THREAD

**Issue by CatNorrius** [TrainerRoshi/Roshi-HHeroes-Trainer#50]
Greetings, Master.
I don’t know why, but the bot interface decided to become like this)
After clearing the cache for 5 seconds, the bot works fine, and then it becomes like this again.
![image](https://user-images.githubusercontent.com/100474910/196889002-aab443e3-088d-40b1-aaa9-dec57edfef44.png)

**Comment by Dragoncca** [comment]
master is big ! 
i like it :D

**Comment by CatNorrius** [comment]
I totally agree.
If there was an opportunity, I would like to return a working bot, but leave the Big Master :D

**Comment by CatNorrius** [comment]
I just want to understand if it’s a jamb for me (I cleared the cache, relogged the computer, etc.) or the developers changed something in the harem.

**Comment by Dragoncca** [comment]
not it's not i got the same

**Comment by kkhosronejad** [comment]
and mine is the same... something has gone wrong

**Comment by CatNorrius** [comment]
It's a little comforting

**Comment by FZN025** [comment]
I`ve noticed, it happened after turn on "blessings"

content.js:2941 Uncaught (in promise) Error: Cannot read properties of null (reading '1')
    at wrappedSendMessageCallback (content.js:2941:18)
userscript.html?name=Master%2520Roshi's%2520HHeroes%2520Trainer.user.js&id=2abbc29f-3f6a-4928-94c7-f33bd8f9eeae:273 Uncaught (in promise) RangeError: Invalid array length
    at createXParray (userscript.html?name=Master%2520Roshi's%2520HHeroes%2520Trainer.user.js&id=2abbc29f-3f6a-4928-94c7-f33bd8f9eeae:273:7508)
    at Proxy.tms_2abbc29f_3f6a_4928_94c7_f33bd8f9eeae$ (userscript.html?name=Master%2520Roshi's%2520HHeroes%2520Trainer.user.js&id=2abbc29f-3f6a-4928-94c7-f33bd8f9eeae:273:8166)
    at it (<anonymous>:14:1074)
    at userscript.html?name=Master%2520Roshi's%2520HHeroes%2520Trainer.user.js&id=2abbc29f-3f6a-4928-94c7-f33bd8f9eeae:1:124
    at userscript.html?name=Master%2520Roshi's%2520HHeroes%2520Trainer.user.js&id=2abbc29f-3f6a-4928-94c7-f33bd8f9eeae:1:571
    at window.__p__5570016.732221662 (userscript.html?name=Master%2520Roshi's%2520HHeroes%2520Trainer.user.js&id=2abbc29f-3f6a-4928-94c7-f33bd8f9eeae:275:6)
    at it (<anonymous>:14:1074)
    at set (<anonymous>:3:400)
    at userscript.html?name=Master%2520Roshi's%2520HHeroes%2520Trainer.user.js&id=2abbc29f-3f6a-4928-94c7-f33bd8f9eeae:1:34
    at it (<anonymous>:14:1074)
content.js:2941 Uncaught (in promise) Error: Cannot read properties of null (reading '1')
    at wrappedSendMessageCallback (content.js:2941:18)
content.js:2941 Uncaught (in promise) Error: Cannot read properties of null (reading '1')
    at wrappedSendMessageCallback (content.js:2941:18)
userscript.html?name=Master%2520Roshi's%2520HHeroes%2520Trainer.user.js&id=2abbc29f-3f6a-4928-94c7-f33bd8f9eeae:273 script started
jquery.min.js:2 jQuery.Deferred exception: Cannot read properties of undefined (reading 'replace') TypeError: Cannot read properties of undefined (reading 'replace')
    at HTMLDocument.start (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?name=Master%2520Roshi's%2520HHeroes%2520Trainer.user.js&id=2abbc29f-3f6a-4928-94c7-f33bd8f9eeae:273:329419)
    at e (https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js:2:30038)
    at t (https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js:2:30340) undefined
S.Deferred.exceptionHook @ jquery.min.js:2
jquery.min.js:2 Uncaught TypeError: Cannot read properties of undefined (reading 'replace')
    at HTMLDocument.start (userscript.html?name=Master%2520Roshi's%2520HHeroes%2520Trainer.user.js&id=2abbc29f-3f6a-4928-94c7-f33bd8f9eeae:273:329419)
    at e (jquery.min.js:2:30038)
    at t (jquery.min.js:2:30340)

**Comment by TrainerRoshi** [comment]
Fixed as of 1.60. Sorry about the delay everyone! I'll include a surprise in 1.61.

**Comment by Dragoncca** [comment]
<3 it's fine :) love ya

**Comment by CatNorrius** [comment]
Master is always the best
